version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.16.2
    working_directory: ~/react-uswds
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1.0.0-dependencies-{{ checksum "package.json" }}
            - v1.0.0-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1.0.0-dependencies-{{ checksum "package.json" }}

      - run: yarn test -w 1

      - run:
          name: 'Happo'
          command: '[[ ( "${CIRCLE_PR_USERNAME}" != "dependabot" ) && ( "${CIRCLE_PR_USERNAME}" != "dependabot-preview" ) ]] && yarn happo-ci'
          environment:
            HAPPO_IS_ASYNC: 'true'
            BASE_BRANCH: 'origin/main'

      - run: yarn lint
      - run: yarn danger ci --failOnErrors
  
  license_finder:
    docker:
      - image: circleci/ruby:2.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1.0.0-dependencies-{{ checksum "package.json" }}
            - v1.0.0-dependencies-
      - run: gem install license_finder
      - run: license_finder

workflows:
  version: 2
  build_and_check_licenses:
    jobs:
      - build
      - license_finder:
          requires:
            - build